//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManyToManyWithData.Tests
{
    using System;
    using System.Collections.Generic;
    
    public partial class actor
    {
        public actor()
        {
            this.performances = new HashSet<performance>();
        }
    
        public int id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<performance> performances { get; set; }
    }
}
