//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManyToManyWithData.Tests
{
    using System;
    using System.Collections.Generic;
    
    public partial class performance
    {
        public int movie_id { get; set; }
        public int actor_id { get; set; }
        public int fee { get; set; }
    
        public virtual actor actor { get; set; }
        public virtual movie movie { get; set; }
    }
}
